import Foundation

public enum FormRole: String, Codable, Hashable, Sendable {
    /// A form with a register, usually a polarity and a tense.
    case finite
    /// The て-form of its family.
    case connective
    /// A form identified by its name alone (ながら).
    case derived
}

public enum FormRegister: String, Codable, Hashable, Sendable {
    case short, polite, casual
}

public enum FormPolarity: String, Codable, Hashable, Sendable {
    case pos, neg
}

public enum FormTense: String, Codable, Hashable, Sendable {
    case present, past
}

public enum FormSource: String, Codable, Hashable, Sendable {
    /// A base form written by hand in the data file.
    case authored
    /// Generated by `scripts/update_data.py`.
    case derived
}

/// A family of forms: a quiz topic and a detail-page section.
public struct FormFamily: Codable, Hashable, Identifiable, Sendable {
    public var id: String
    public var title: String
}

/// What one form id means. Mirrors an entry of `forms.json`, which is generated
/// from `scripts/form_catalogue.py`.
public struct FormSpec: Codable, Hashable, Identifiable, Sendable {
    public var id: FormID
    /// The id of a `FormFamily`.
    public var family: String
    /// "Polite · past", "Potential · polite · past": built from the facets.
    public var label: String
    /// "Potential", "ている": what the form is when it is not a plain conjugation.
    public var name: String?
    public var role: FormRole
    public var register: FormRegister?
    public var polarity: FormPolarity?
    public var tense: FormTense?
    public var appliesTo: [WordClass]
    public var source: FormSource
    /// The id of the grammar lesson this form belongs to.
    public var grammar: String?
    /// Whether verb search matches this form.
    public var search: Bool
    /// Equates forms with different ids across word classes.
    public var concept: String?

    enum CodingKeys: String, CodingKey {
        case id, family, label, name, role, register, polarity, tense
        case appliesTo = "applies_to"
        case source, grammar, search, concept
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(FormID.self, forKey: .id)
        family = try c.decode(String.self, forKey: .family)
        label = try c.decode(String.self, forKey: .label)
        name = try c.decodeIfPresent(String.self, forKey: .name)
        role = try c.decode(FormRole.self, forKey: .role)
        register = try c.decodeIfPresent(FormRegister.self, forKey: .register)
        polarity = try c.decodeIfPresent(FormPolarity.self, forKey: .polarity)
        tense = try c.decodeIfPresent(FormTense.self, forKey: .tense)
        appliesTo = try c.decode([WordClass].self, forKey: .appliesTo)
        source = try c.decode(FormSource.self, forKey: .source)
        grammar = try c.decodeIfPresent(String.self, forKey: .grammar)
        search = try c.decodeIfPresent(Bool.self, forKey: .search) ?? false
        concept = try c.decodeIfPresent(String.self, forKey: .concept)
    }
}

/// Every conjugation form the app knows, in the order of the data files'
/// `forms` objects. The UI and quiz iterate this; they never guess which forms
/// a word class has.
public struct FormCatalogue: Sendable {
    public let schema: Int
    public let families: [FormFamily]
    /// All forms, in catalogue order.
    public let forms: [FormSpec]
    private let byID: [FormID: FormSpec]

    private struct Document: Decodable {
        var schema: Int
        var families: [FormFamily]
        var forms: [FormSpec]
    }

    /// Decodes a `forms.json` document.
    public init(data: Data) throws {
        let document = try JSONDecoder().decode(Document.self, from: data)
        self.schema = document.schema
        self.families = document.families
        self.forms = document.forms
        self.byID = Dictionary(document.forms.map { ($0.id, $0) }, uniquingKeysWith: { first, _ in first })
    }

    /// The catalogue bundled with the app. A missing or malformed resource is a
    /// build error, not a runtime condition, so it stops the app.
    public static let bundled: FormCatalogue = {
        guard let url = Bundle.module.url(forResource: "forms", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let catalogue = try? FormCatalogue(data: data)
        else {
            fatalError("VerbKit's bundled forms.json is missing or malformed")
        }
        return catalogue
    }()

    public func spec(for id: FormID) -> FormSpec? {
        byID[id]
    }

    public func family(_ id: String) -> FormFamily? {
        families.first { $0.id == id }
    }

    /// The forms that apply to `wordClass`, in catalogue order, optionally
    /// narrowed to one family.
    public func specs(for wordClass: WordClass, family: String? = nil) -> [FormSpec] {
        forms.filter { $0.appliesTo.contains(wordClass) && (family == nil || $0.family == family) }
    }

    /// The forms of `wordClass` that `conjugations` has a non-empty string for,
    /// in catalogue order, with that string.
    public func available(
        in conjugations: Conjugations, for wordClass: WordClass, family: String? = nil
    ) -> [(spec: FormSpec, value: String)] {
        specs(for: wordClass, family: family).compactMap { spec in
            guard let value = conjugations[spec.id], !value.isEmpty else { return nil }
            return (spec, value)
        }
    }
}
