import Foundation

/// The published `words.json`: adjectives and nouns whose forms are generated by
/// `scripts/update_data.py`. Grammar patterns are built from these forms.
public struct WordsDataFile: Decodable, Sendable {
    public var version: String
    public var description: String
    public var words: [Word]

    enum CodingKeys: String, CodingKey {
        case version, description, words
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        version = try c.decode(String.self, forKey: .version)
        description = try c.decode(String.self, forKey: .description)
        words = try c.decode([StoredWord].self, forKey: .words).map(\.word)
    }
}

/// One word as it is written in words.json and in the cache. Only the fields a word from
/// words.json has; verbs keep their own format.
struct StoredWord: Codable, Equatable, Sendable {
    var wordClass: WordClass
    var dict: String
    var kanji: String?
    var meaning: String
    var jlpt: JLPTLevel?
    var forms: Conjugations

    enum CodingKeys: String, CodingKey {
        case wordClass = "class", dict, kanji, meaning, jlpt, forms
    }

    init(_ word: Word) {
        wordClass = word.wordClass
        dict = word.dict
        kanji = word.kanji
        meaning = word.meaning
        jlpt = word.jlpt
        forms = word.forms
    }

    var word: Word {
        Word(wordClass: wordClass, dict: dict, kanji: kanji, meaning: meaning, description: "", jlpt: jlpt, forms: forms)
    }
}
