"""The catalogue of conjugation forms: the one place a form id is declared.

A form is identified by a stable snake_case `id` (the key used in the `forms`
object of the data files) and described here: which family (quiz topic and
detail-page section) it belongs to, its facets (role, register, polarity,
tense), the word classes it applies to, and whether it is authored by hand or
derived by `update_data.py`.

`update_data.py` owns the endings (the rules); this module owns the ids, their
order and their meaning. It also publishes itself as `forms.json`, which the
app reads for labels, topics and display order, so the app never re-declares
an id.

Standard library only.
"""
from dataclasses import dataclass
from typing import Optional

WORD_CLASSES = ("verb", "i-adjective", "na-adjective", "noun")

# (id, title) in display order. A family is a quiz topic and a detail-page
# section; it is data here, not an enum in the app.
FAMILIES = (
    ("basic", "Basic forms"),
    ("potential", "Potential"),
    ("nd", "んです"),
    ("auxiliary", "Auxiliaries"),
    ("other", "More forms"),
)

ROLES = ("finite", "connective", "derived")
REGISTERS = ("short", "polite", "casual")
POLARITIES = ("pos", "neg")
TENSES = ("present", "past")
SOURCES = ("authored", "derived")

# How a register is worded in a label.
_REGISTER_TEXT = {"short": "plain", "polite": "polite", "casual": "casual"}


@dataclass(frozen=True)
class FormSpec:
    id: str
    family: str
    # "finite": a form with a register (and usually a polarity and tense).
    # "connective": the て-form of its family.
    # "derived": a form identified by its name alone (ながら).
    role: str = "finite"
    register: Optional[str] = None
    polarity: Optional[str] = None
    tense: Optional[str] = None
    # The word the form belongs to when it is not a plain conjugation:
    # "Potential", "ている", "すぎる". None for the basic forms.
    name: Optional[str] = None
    applies_to: tuple = ("verb",)
    # "authored": base form written by hand. "derived": generated by the script.
    source: str = "derived"
    # The id of the lesson in grammar.json this form belongs to.
    grammar: Optional[str] = None
    # Whether verb search matches the form.
    search: bool = False
    # Equates forms with different ids across word classes (the verbs' masu_*
    # and the other classes' polite_*). Only set where ids differ by class.
    concept: Optional[str] = None

    @property
    def label(self):
        """"Polite · past", "Potential · polite · past", "ている · て-form".
        Built from facets so labels are never hand-written."""
        if self.role == "connective":
            register = "て-form"
        else:
            register = _REGISTER_TEXT.get(self.register)
        if self.name is None and register is not None:
            register = register[0].upper() + register[1:]
        parts = [
            self.name,
            register,
            "past" if self.tense == "past" else None,
            "negative" if self.polarity == "neg" else None,
        ]
        return " · ".join(part for part in parts if part)

    def to_json(self):
        """The spec as published in forms.json: facets that are None are left out."""
        raw = {
            "id": self.id,
            "family": self.family,
            "label": self.label,
            "name": self.name,
            "role": self.role,
            "register": self.register,
            "polarity": self.polarity,
            "tense": self.tense,
            "applies_to": list(self.applies_to),
            "source": self.source,
            "grammar": self.grammar,
            "search": self.search or None,
            "concept": self.concept,
        }
        return {key: value for key, value in raw.items() if value is not None}


def _grid(prefix, family, name, register, grammar, *, base_id=None):
    """The four finite forms of one register: pos, neg, past, past_neg.
    `base_id` overrides the id of the positive form (`teiru`, not `teiru_pos`)."""
    ids = (base_id or prefix + "pos", prefix + "neg", prefix + "past", prefix + "past_neg")
    combos = (("pos", "present"), ("neg", "present"), ("pos", "past"), ("neg", "past"))
    return [
        FormSpec(
            id=form_id, family=family, name=name, register=register,
            polarity=polarity, tense=tense, grammar=grammar,
        )
        for form_id, (polarity, tense) in zip(ids, combos)
    ]


def _build():
    forms = []

    # Basic forms: authored by hand for every verb. Same facets as the polite
    # and plain grids; the masu_* ids carry a concept so the other word classes'
    # polite_* forms can be matched to them.
    for form_id, (polarity, tense) in zip(
        ("masu_pos", "masu_neg", "masu_past", "masu_past_neg"),
        (("pos", "present"), ("neg", "present"), ("pos", "past"), ("neg", "past")),
    ):
        forms.append(FormSpec(
            id=form_id, family="basic", register="polite", polarity=polarity, tense=tense,
            source="authored", search=True, concept=f"polite.{polarity}.{tense}",
        ))
    forms.append(FormSpec(
        id="te", family="basic", role="connective", source="authored", search=True, concept="te",
        applies_to=WORD_CLASSES,
    ))
    for form_id, (polarity, tense) in zip(
        ("short_pos", "short_neg", "short_past", "short_past_neg"),
        (("pos", "present"), ("neg", "present"), ("pos", "past"), ("neg", "past")),
    ):
        forms.append(FormSpec(
            id=form_id, family="basic", register="short", polarity=polarity, tense=tense,
            source="authored", search=True, concept=f"short.{polarity}.{tense}",
            applies_to=WORD_CLASSES,
        ))

    # んです: the plain forms + んです (polite) or んだ (casual).
    forms += _grid("nd_", "nd", "んです", "polite", "n-desu")
    forms += _grid("nd_casual_", "nd", "んです", "casual", "n-desu")

    # Potential: the base form, then the potential verb's own grid.
    forms.append(FormSpec(
        id="potential", family="potential", name="Potential", register="short",
        polarity="pos", tense="present", grammar="potential",
    ))
    forms += [
        FormSpec(id="pot_masu_pos", family="potential", name="Potential", register="polite",
                 polarity="pos", tense="present", grammar="potential"),
        FormSpec(id="pot_masu_neg", family="potential", name="Potential", register="polite",
                 polarity="neg", tense="present", grammar="potential"),
        FormSpec(id="pot_masu_past", family="potential", name="Potential", register="polite",
                 polarity="pos", tense="past", grammar="potential"),
        FormSpec(id="pot_masu_past_neg", family="potential", name="Potential", register="polite",
                 polarity="neg", tense="past", grammar="potential"),
        FormSpec(id="pot_te", family="potential", role="connective", name="Potential",
                 grammar="potential"),
        FormSpec(id="pot_short_neg", family="potential", name="Potential", register="short",
                 polarity="neg", tense="present", grammar="potential"),
        FormSpec(id="pot_short_past", family="potential", name="Potential", register="short",
                 polarity="pos", tense="past", grammar="potential"),
        FormSpec(id="pot_short_past_neg", family="potential", name="Potential", register="short",
                 polarity="neg", tense="past", grammar="potential"),
    ]

    # Auxiliaries. ている is conjugated in full: a plain grid, a polite grid, a て-form.
    forms += _grid("teiru_", "auxiliary", "ている", "short", "teiru", base_id="teiru")
    forms += _grid("teiru_masu_", "auxiliary", "ている", "polite", "teiru")
    forms.append(FormSpec(
        id="teiru_te", family="auxiliary", role="connective", name="ている", grammar="teiru",
    ))
    # The other auxiliaries have a plain and a polite form (ながら has one).
    for form_id, name, grammar in (
        ("teshimau", "てしまう", "teshimau"),
        ("teoku", "ておく", "teshimau"),
        ("temiru", "てみる", "temiru"),
        ("sugiru", "すぎる", "sugiru"),
        ("yasui", "やすい", "sugiru"),
        ("nikui", "にくい", "sugiru"),
    ):
        forms.append(FormSpec(
            id=form_id, family="auxiliary", name=name, register="short", grammar=grammar,
        ))
        forms.append(FormSpec(
            id=form_id + "_polite", family="auxiliary", name=name, register="polite",
            grammar=grammar,
        ))
    forms.append(FormSpec(
        id="nagara", family="auxiliary", role="derived", name="ながら", grammar="temiru",
    ))

    # More forms: each is identified by its name alone, so it is "derived". No
    # lessons yet. ある has only some of them (update_data.py decides which).
    for form_id, name in (
        ("volitional", "Volitional"),
        ("passive", "Passive"),
        ("causative", "Causative"),
        ("causative_passive", "Causative-passive"),
        ("conditional_ba", "Conditional (ば)"),
        ("conditional_tara", "Conditional (たら)"),
        ("imperative", "Imperative"),
        ("tai", "たい (want to)"),
    ):
        forms.append(FormSpec(id=form_id, family="other", role="derived", name=name))
    return forms


# Order is the order of the keys in the data files' `forms` objects.
FORMS = tuple(_build())

_BY_ID = {spec.id: spec for spec in FORMS}


def spec(form_id):
    """The FormSpec for an id, or None if the catalogue has no such form."""
    return _BY_ID.get(form_id)


def ids(word_class, family=None, source=None):
    """Form ids that apply to `word_class`, in catalogue order, optionally
    narrowed to one family and/or source."""
    return [
        s.id for s in FORMS
        if word_class in s.applies_to
        and (family is None or s.family == family)
        and (source is None or s.source == source)
    ]


def to_json_doc():
    """The document published as forms.json."""
    return {
        "schema": 1,
        "description": (
            "Catalogue of conjugation forms. Generated by scripts/update_data.py "
            "from scripts/form_catalogue.py; do not edit by hand."
        ),
        "word_classes": list(WORD_CLASSES),
        "families": [{"id": family_id, "title": title} for family_id, title in FAMILIES],
        "forms": [s.to_json() for s in FORMS],
    }


def problems():
    """Catalogue invariants as a list of messages (empty when sound)."""
    found = []
    seen = set()
    family_ids = {family_id for family_id, _ in FAMILIES}
    for s in FORMS:
        if s.id in seen:
            found.append(f"duplicate form id {s.id}")
        seen.add(s.id)
        if s.family not in family_ids:
            found.append(f"{s.id}: unknown family {s.family}")
        if s.role not in ROLES:
            found.append(f"{s.id}: unknown role {s.role}")
        if s.register is not None and s.register not in REGISTERS:
            found.append(f"{s.id}: unknown register {s.register}")
        if s.polarity is not None and s.polarity not in POLARITIES:
            found.append(f"{s.id}: unknown polarity {s.polarity}")
        if s.tense is not None and s.tense not in TENSES:
            found.append(f"{s.id}: unknown tense {s.tense}")
        if s.source not in SOURCES:
            found.append(f"{s.id}: unknown source {s.source}")
        for word_class in s.applies_to:
            if word_class not in WORD_CLASSES:
                found.append(f"{s.id}: unknown word class {word_class}")
    return found
